### ISSUE TITLE
Runs with MySQL replicas enabled are failing

### ISSUE THREAD

**Issue by vmdef** [moodlehq/moodle-ci-runner#80]
Testing a patch related to database replication,  builds with MySQL replica set fail:

Build: https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/7848/

Error in **3. Section Database summary**:

> mysqld: File '/var/log/mysql/mysql-bin.index' not found (Errcode: 2 - No such file or directory)
2022-08-23T10:21:41.025184Z 0 [ERROR] Aborting

**Comment by stronk7** [comment]
Problems seems to be that the `/var/log/mysql`directory doesn't exist in the `mysql:5.7` images anymore:

```
$ docker run --rm mysql:5.7 ls -al /var/log
total 16
drwxr-xr-x 1 root  root  4096 Jul 26 23:29 .
drwxr-xr-x 1 root  root  4096 Jul  1 20:47 ..
-rw-r----- 1 mysql mysql    0 Jul 26 23:29 mysqld.log
-rw------- 1 root  root  6932 Jul 26 23:29 yum.log
```

But it was there in previous versions, see for example `mysql:5.6`:

```
$ docker run --rm mysql:5.6 ls -al /var/log
total 376
drwxr-xr-x 1 root  root   4096 Dec 21  2021 .
drwxr-xr-x 1 root  root   4096 Dec 20  2021 ..
-rw-r--r-- 1 root  root   2484 Dec 21  2021 alternatives.log
drwxr-xr-x 1 root  root   4096 Dec 21  2021 apt
-rw-rw---- 1 root  utmp      0 Dec 20  2021 btmp
-rw-r--r-- 1 root  root  36363 Dec 21  2021 dpkg.log
-rw-r--r-- 1 root  root  32000 Dec 21  2021 faillog
-rw-rw-r-- 1 root  utmp 292000 Dec 21  2021 lastlog
drwxr-x--- 2 mysql adm    4096 Dec 21  2021 mysql
-rw-rw-r-- 1 root  utmp      0 Dec 20  2021 wtmp
```

So I'm going to find an alternative place to put those binary logs... let's see.

Ciao :-)

**Comment by stronk7** [comment]
Ok, confirmed, I've just changed from `/var/log/mysql` to '/var/lib/mysql` and now both the principal and replica databases are starting ok locally, here it's the output running phpunit (only 1 small suite). Everything finished ok, but still there is some problem with the replica database (`Exited (127)`), that did not start correctly, because docker is telling us that is was down when trying to stop all the containers:

```
== Exit code: 0
============================================================================

>>> startsection Cleaning up docker images <<<
============================================================================
Stopping all docker images for f7472ea8a882f36c
...
...
c38c0d524880   mysql:5.7                            "docker-entrypoint.s…"   3 minutes ago   Exited (127) 2 minutes ago                         databasef7472ea8a882f36c_slave
877db37b71c9   mysql:5.7                            "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes                 3306/tcp, 33060/tcp   databasef7472ea8a882f36c
```

I'll investigate what's going with the replica tomorrow, so far I only have found this in replica logs:

```
2022-08-23 22:25:04+00:00 [Note] [Entrypoint]: Creating database moodle
2022-08-23 22:25:04+00:00 [Note] [Entrypoint]: Creating user moodle
2022-08-23 22:25:04+00:00 [Note] [Entrypoint]: Giving user moodle access to schema moodle

2022-08-23 22:25:04+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/10_replicate.sh
============================================================================
== 10_replicate.sh
============================================================================
/docker-entrypoint-initdb.d/10_replicate.sh: line 14: docker_temp_server_stop: command not found
```

Ciao :-)

**Comment by scara** [comment]
Hi Eloy,
`docker_temp_server_stop` is declared in [docker-entrypoint.sh](https://github.com/docker-library/mysql/blob/f1f8eea87223e7c501c16fab7c4e8e023d42a896/5.7/docker-entrypoint.sh) and [`docker_process_init_files`](https://github.com/docker-library/mysql/commit/b1c48f6f42aea03d24886e914e98c1c71daa3529#diff-525045460e0674a1f9f35d77c66efdece3921dce639cecc6b25018b487958681R61-R71) doesn't "source" `10_replicate.sh` since it is [executable](https://github.com/moodlehq/moodle-ci-runner/commit/bf5d2db9b89bb31e56469ddbf92eb8af719becfb).

I'm not understanding why the _replica container_ is complaining only now: those changes are there since months.

HTH,
Matteo

**Comment by stronk7** [comment]
Hi, yeah... I saw that sourced call... what I've been working on is about to understand why we need to stop and start the database at all, it seems that all the operations can be done in the temp database and then, the entry point itself will stop the database and start the final one...

Right now I've it working with mysql:5.7 and I'm testing also mysql:8.0, because there are some changes related to both authentication/passwords and also changed GRANT command stuff.

Will share a PR soon... hopefully killing the need to stop/start and also the `gosu` uses ... let's see...
